[versions]
agp = "8.10.0"
kotlin = "2.2.0"
muzeiApi = "3.0.0"
jsoup = "1.21.1"

[libraries]
muzei-api = { group = "com.google.android.apps.muzei", name = "muzei-api", version.ref = "muzeiApi" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

